const dogs = [
    { name: "Лабрадор-ретривер", size: "большой", coat: "короткая", purpose: "компаньон", activity: "высокая", apartment: "нет", country: "Канада", life: "10-12 лет" },
    { name: "Немецкая овчарка", size: "большой", coat: "средняя", purpose: "служебная", activity: "высокая", apartment: "нет", country: "Германия", life: "9-13 лет" },
    { name: "Золотистый ретривер", size: "большой", coat: "длинная", purpose: "компаньон", activity: "высокая", apartment: "нет", country: "Великобритания", life: "10-12 лет" },
    { name: "Французский бульдог", size: "маленький", coat: "короткая", purpose: "компаньон", activity: "низкая", apartment: "да", country: "Франция", life: "10-12 лет" },
    { name: "Бульдог", size: "средний", coat: "короткая", purpose: "компаньон", activity: "низкая", apartment: "да", country: "Великобритания", life: "8-10 лет" },
    { name: "Такса", size: "маленький", coat: "короткая", purpose: "охотничья", activity: "средняя", apartment: "да", country: "Германия", life: "12-16 лет" },
    { name: "Сибирский хаски", size: "большой", coat: "средняя", purpose: "служебная", activity: "высокая", apartment: "нет", country: "Россия", life: "12-14 лет" },
    { name: "Пудель", size: "средний", coat: "кудрявая", purpose: "компаньон", activity: "высокая", apartment: "да", country: "Франция", life: "12-15 лет" },
    { name: "Бигль", size: "маленький", coat: "короткая", purpose: "охотничья", activity: "высокая", apartment: "да", country: "Великобритания", life: "12-15 лет" },
    { name: "Ротвейлер", size: "большой", coat: "короткая", purpose: "охранная", activity: "средняя", apartment: "нет", country: "Германия", life: "8-10 лет" },
    { name: "Йоркширский терьер", size: "маленький", coat: "длинная", purpose: "компаньон", activity: "средняя", apartment: "да", country: "Великобритания", life: "13-16 лет" },
    { name: "Доберман", size: "большой", coat: "короткая", purpose: "охранная", activity: "высокая", apartment: "нет", country: "Германия", life: "10-12 лет" },
    { name: "Немецкий дог", size: "гигантский", coat: "короткая", purpose: "компаньон", activity: "средняя", apartment: "нет", country: "Германия", life: "6-8 лет" },
    { name: "Австралийская овчарка", size: "средний", coat: "средняя", purpose: "пастушья", activity: "высокая", apartment: "нет", country: "США", life: "12-15 лет" },
    { name: "Померанский шпиц", size: "маленький", coat: "длинная", purpose: "компаньон", activity: "средняя", apartment: "да", country: "Германия", life: "12-16 лет" },
    { name: "Ши-тцу", size: "маленький", coat: "длинная", purpose: "компаньон", activity: "низкая", apartment: "да", country: "Китай", life: "10-16 лет" },
    { name: "Бостон-терьер", size: "маленький", coat: "короткая", purpose: "компаньон", activity: "средняя", apartment: "да", country: "США", life: "11-13 лет" },
    { name: "Мопс", size: "маленький", coat: "короткая", purpose: "компаньон", activity: "низкая", apartment: "да", country: "Китай", life: "12-15 лет" },
    { name: "Боксер", size: "большой", coat: "короткая", purpose: "охранная", activity: "высокая", apartment: "нет", country: "Германия", life: "10-12 лет" },
    { name: "Такса миниатюрная", size: "маленький", coat: "короткая", purpose: "охотничья", activity: "средняя", apartment: "да", country: "Германия", life: "12-16 лет" },
    { name: "Чихуахуа", size: "маленький", coat: "короткая", purpose: "компаньон", activity: "средняя", apartment: "да", country: "Мексика", life: "12-20 лет" },
    { name: "Мальтийская болонка", size: "маленький", coat: "длинная", purpose: "компаньон", activity: "низкая", apartment: "да", country: "Мальта", life: "12-15 лет" },
    { name: "Колли", size: "большой", coat: "длинная", purpose: "пастушья", activity: "высокая", apartment: "нет", country: "Шотландия", life: "12-14 лет" },
    { name: "Кокер-спаниель", size: "средний", coat: "длинная", purpose: "охотничья", activity: "высокая", apartment: "да", country: "Великобритания", life: "12-15 лет" },
    { name: "Вельш-корги", size: "маленький", coat: "средняя", purpose: "пастушья", activity: "высокая", apartment: "да", country: "Уэльс", life: "12-15 лет" },
    { name: "Самоед", size: "большой", coat: "длинная", purpose: "служебная", activity: "высокая", apartment: "нет", country: "Россия", life: "12-14 лет" },
    { name: "Акита-ину", size: "большой", coat: "средняя", purpose: "охранная", activity: "средняя", apartment: "нет", country: "Япония", life: "10-13 лет" },
    { name: "Бассет-хаунд", size: "средний", coat: "короткая", purpose: "охотничья", activity: "низкая", apartment: "да", country: "Франция", life: "10-12 лет" },
    { name: "Мастиф", size: "гигантский", coat: "короткая", purpose: "охранная", activity: "низкая", apartment: "нет", country: "Великобритания", life: "6-10 лет" },
    { name: "Бордер-колли", size: "средний", coat: "средняя", purpose: "пастушья", activity: "высокая", apartment: "нет", country: "Великобритания", life: "12-15 лет" },
    { name: "Питбуль", size: "средний", coat: "короткая", purpose: "компаньон", activity: "высокая", apartment: "нет", country: "США", life: "12-14 лет" },
    { name: "Шарпей", size: "средний", coat: "короткая", purpose: "охранная", activity: "низкая", apartment: "да", country: "Китай", life: "8-12 лет" },
    { name: "Веймаранер", size: "большой", coat: "короткая", purpose: "охотничья", activity: "высокая", apartment: "нет", country: "Германия", life: "10-13 лет" },
    { name: "Кавалер-кинг-чарльз-спаниель", size: "маленький", coat: "длинная", purpose: "компаньон", activity: "средняя", apartment: "да", country: "Великобритания", life: "9-14 лет" },
    { name: "Бернский зенненхунд", size: "гигантский", coat: "длинная", purpose: "служебная", activity: "средняя", apartment: "нет", country: "Швейцария", life: "7-10 лет" },
    { name: "Чау-чау", size: "средний", coat: "длинная", purpose: "охранная", activity: "низкая", apartment: "да", country: "Китай", life: "9-12 лет" },
    { name: "Далматин", size: "большой", coat: "короткая", purpose: "компаньон", activity: "высокая", apartment: "нет", country: "Хорватия", life: "10-13 лет" },
    { name: "Английский сеттер", size: "большой", coat: "средняя", purpose: "охотничья", activity: "высокая", apartment: "нет", country: "Великобритания", life: "10-12 лет" },
    { name: "Ирландский волкодав", size: "гигантский", coat: "жёсткая", purpose: "охотничья", activity: "средняя", apartment: "нет", country: "Ирландия", life: "6-8 лет" },
    { name: "Португальская водяная собака", size: "средний", coat: "кудрявая", purpose: "служебная", activity: "высокая", apartment: "да", country: "Португалия", life: "11-13 лет" },
    { name: "Скай-терьер", size: "маленький", coat: "длинная", purpose: "охотничья", activity: "средняя", apartment: "да", country: "Шотландия", life: "12-14 лет" },
    { name: "Афганская борзая", size: "большой", coat: "длинная", purpose: "охотничья", activity: "высокая", apartment: "нет", country: "Афганистан", life: "12-14 лет" },
    { name: "Басенджи", size: "маленький", coat: "короткая", purpose: "охотничья", activity: "высокая", apartment: "да", country: "Центральная Африка", life: "13-14 лет" },
    { name: "Китайская хохлатая", size: "маленький", coat: "без шерсти", purpose: "компаньон", activity: "средняя", apartment: "да", country: "Китай", life: "13-15 лет" },
    { name: "Лхаса апсо", size: "маленький", coat: "длинная", purpose: "компаньон", activity: "средняя", apartment: "да", country: "Тибет", life: "12-15 лет" },
    { name: "Ньюфаундленд", size: "гигантский", coat: "длинная", purpose: "служебная", activity: "средняя", apartment: "нет", country: "Канада", life: "8-10 лет" },
    { name: "Папильон", size: "маленький", coat: "длинная", purpose: "компаньон", activity: "высокая", apartment: "да", country: "Франция", life: "13-15 лет" },
    { name: "Родезийский риджбек", size: "большой", coat: "короткая", purpose: "охотничья", activity: "высокая", apartment: "нет", country: "Зимбабве", life: "10-12 лет" },
    { name: "Сенбернар", size: "гигантский", coat: "длинная", purpose: "служебная", activity: "низкая", apartment: "нет", country: "Швейцария", life: "8-10 лет" },
    { name: "Вести", size: "маленький", coat: "длинная", purpose: "охотничья", activity: "высокая", apartment: "да", country: "Шотландия", life: "12-16 лет" }
];